config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rooms import views as room_views
from users import views as user_views


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"


urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]


rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]


users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("login/naver/", views.naver_login, name="naver-login"),
    path("login/naver/callback/", views.naver_callback, name="naver-callback"),
    # path("login/google/", views.google_login, name="google-login"),
    # path("login/google/callback/", views.google_callback, name="google-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>", views.UserProfileView.as_view(), name="profile"),
    path("switch-language/", views.switch_language, name="switch-language"),
]


templates/partials/footer.html
{% load i18n %}

<div class="border-t max-w-full xl: mt-20 lg: mt-10 md: mt-4 sm: mt-0"></div>
<footer class="container xl:max-w-5xl mx-auto lg: max-w-5xl mx-auto py-8 font-medium text-gray-700 text-sm">
  <div class="grid grid-cols-12 gap-5">
    <div class="xl:col-span-3 lg:col-span-3 mb-10 w-full">
      <div class="mb-4"><span class="font-semibold">{% trans "Booking" %}</span></div>
      <div>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '채용정보' %} </a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '뉴스' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '정책' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '다양성과 소속감' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '접근성' %}</a>
      </div>
    </div>
    <div class="xl:col-span-3 lg:col-span-3 mb-10 w-full">
      <div class="mb-4"><span class="font-semibold">{% trans '여행하기' %}</span></div>
      <div>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '신뢰와 안전' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '여행 크레딧' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '비즈니스 프로그램' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '즐길거리' %}</a>
      </div>
    </div>
    <div class="xl:col-span-3 lg:col-span-3 mb-10 w-full">
      <div class="mb-4"><span class="font-semibold">{% trans '호스팅하기' %}</span></div>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '호스팅의 장점' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '호스트 추천하기' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '호스팅 기준' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '책임감 있는 호스팅 하기' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '커뮤니티 센터' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '체험 호스팅' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans 'Open Homes 프로그램' %}</a>
      </div>
    <div class="xl:col-span-3 lg:col-span-3 mb-10 w-full">
      <div class="mb-4"><span class="font-semibold">{% trans '고객지원' %}</span></div>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '도움말' %}</a>
        <a class="block hover:underline" href="{% url 'core:home' %}">{% trans '정이웃 민원 지원' %}</a>
      </div>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="message overflow-x-hidden overflow-y-hidden z-20 fixed top-0 mt-10 w-64 h-64 mx-auto left-0 right-0 flex justify-center">
        {% for message in messages %}
            <li class="message font-medium bg-white rounded-md text-black w-64 h-64 py-4 px-6 z-20 text-center {% if message.tags %}{{ message.tags }}{% endif %}">
                <div class="flex justify-center items-center w-32 bg-transparent rounded-full h-32 mx-auto mb-4">
                    {% if message.tags == "success" %}
                        <i class="fa fa-check-circle fa-8x text-green-500"></i>
                    {% elif message.tags == "error" %}
                        <i class="fa fa-exclamation-triangle fa-6x text-red-500"></i>
                    {% elif message.tags == "info" %}
                        <i class="fas fa-info-circle fa-6x text-blue-500"></i>
                    {% endif %}
                </div>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %} 

templates/partials/nav.html
{% load i18n %}
<ul class="nav-links flex text-sm font-medium h-full" id="js-myTopnav">
  <li class="nav_link xl:h-full lg:h-full">
    <div class="inline bg-white">
      {% get_current_language as LANGUAGE_CODE %}
      <select class="cursor-pointer text-sm select-hide" id="js-lang">
        <option value="kr"
        {% if LANGUAGE_CODE == 'kr' %}
          selected
        {% endif %}>{% trans '한국어' %} </option>
        <option value="en"
        {% if LANGUAGE_CODE == 'en' %}
          selected
        {% endif %}>{% trans '영어' %}</option>
      </select>
    </a>
  </li>
  {% if user.is_authenticated %}
    <li class="nav_link xl:h-full lg:h-full"><a href="{% url 'rooms:create' %}">{% trans '숙소 등록' %}</a></li>
    <li class="nav_link xl:h-full lg:h-full"><a href="{{user.get_absolute_url}}">{% trans '프로필' %}</a></li>
    <li class="nav_link xl:h-full lg:h-full"><a href="{% url 'users:logout' %}">{% trans '로그아웃' %}</a></li>
  {% else %}
    <li class="nav_link xl:h-full lg:h-full"><a href="{% url 'users:login' %}">{% trans '로그인' %}</a></li>
    <li class="nav_link xl:h-full lg:h-full"><a href="{% url 'users:signup' %}">{% trans '회원가입' %}</a></li>
  {% endif %}
</ul>
<div class="burger">
  <div class="line1"></div>
  <div class="line2"></div>
  <div class="line3"></div>
</div>
<script>
  
</script>


templates/partials/social_login.html
{% load static i18n %}
<div class="flex flex-col w-full">
  <a href="{% url 'users:naver-login' %}" class="btn border text-white mb-2 border-green-400 bg-naver">
    <img class="w-6 inline" src="{% static 'img/naver_icon.png' %}" >&nbsp
    {% trans '네이버로 로그인' %}
  </a>
  <a href="{% url 'users:kakao-login' %}" class="btn border text-yellow-800 mb-2 border-yellow-400 bg-yellow-400 ">
    <i class="fas fa-comment mr-2 fa-lg"></i>
    {% trans '카카오로 로그인' %}
  </a>
  <a href="{% url 'users:github-login' %}" class="btn border-2 text-gray-700 mb-2 border-gray-700">
    <i class="fab fa-github mr-2 fa-lg"></i>
    {% trans '깃허브로 로그인' %}
  </a>
</div>

<div class="flex items-center w-full my-5">
  <div class="h-px w-full bg-gray-400"></div>
  <span class="text-gray-600 font-medium mx-4 w-20 text-sm text-center">{% trans '또는' %}</span>
  <div class="h-px w-full bg-gray-400"></div>
</div>