config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rooms import views as room_views
from users import views as user_views


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"


urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]


lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]


reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("list/", views.seeReservationView.as_view(), name="see-reservation"),
]


rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
]


rooms/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):
    city = forms.CharField(label=_("도시"), initial="모든 곳")
    country = CountryField(default="KR").formfield()
    price = forms.IntegerField(label=_("가격"), required=False)
    room_type = forms.ModelChoiceField(
        label=_("숙소 유형"),
        required=False,
        empty_label="모든 숙소 유형",
        queryset=models.RoomType.objects.all(),
    )
    guests = forms.IntegerField(
        label=_("게스트"), required=False, min_value=1, max_value=9
    )
    bedrooms = forms.IntegerField(
        label=_("침실"), required=False, min_value=1, max_value=9
    )
    beds = forms.IntegerField(label=_("침대"), required=False, min_value=1, max_value=9)
    baths = forms.IntegerField(label=_("욕실"), required=False, min_value=1, max_value=9)
    instant_book = forms.BooleanField(label=_("즉시예약"), required=False)
    superhost = forms.BooleanField(label=_("슈퍼호스트"), required=False)
    amenities = forms.ModelMultipleChoiceField(
        label=_("편의시설"),
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        label=_("시설"),
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

        widgets = {
            "caption": forms.TextInput(attrs={"autocomplete": "off"}),
        }

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

        widgets = {
            "name": forms.TextInput(attrs={"autocomplete": "off"}),
            "city": forms.TextInput(attrs={"autocomplete": "off"}),
            "address": forms.TextInput(attrs={"autocomplete": "off"}),
            "check_in": forms.TextInput(
                attrs={"placeholder": "17:12:34", "autocomplete": "off"}
            ),
            "check_out": forms.TextInput(
                attrs={"placeholder": "17:12:34", "autocomplete": "off"}
            ),
        }

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms

# Create your views here.
class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


class RoomDetail(user_mixins.LoggedInOnlyView, DetailView):

    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):

        city = request.GET.get("city")
        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "모든 곳":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")
                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)
                return render(
                    request, "rooms/room_search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/room_search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
        "instant_book",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "지울 수 없습니다.")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "사진이 삭제되었습니다.")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "사진이 수정되었습니다."
    fields = ("caption",)

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["caption"].widget.attrs = {"autocomplete": "off"}
        return form

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    model = models.Photo
    template_name = "rooms/photo_create.html"
    fields = ("file", "caption")
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "사진이 업로드되었습니다.")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "숙소가 등록되었습니다.")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    사진 추가
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="사진 업로드" %}

    </div>
{% endblock content %} 

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
    사진 수정
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="사진 수정완료" %}

    </div>
{% endblock content %} 

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
    숙소 등록
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="숙소 등록하기" %}

    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked on_favs %}

{% block page_title %}
    {{room.name}} | Booking
{% endblock page_title %}

{% block content %}
    <div>
        {% on_favs room as on_favs_boolean %}
        {% if on_favs_boolean %}
            {% if user != room.host %}
                <a href="{% url 'lists:toggle-room' room.pk %}?action=remove">
                    <i class="fas fa-heart fa-2x text-red-600 absolute" style="z-index: 5; top:90px; right:14px;"></i>
                </a>
            {% endif %}
        {% else %}
            {% if user != room.host %}
                <a href="{% url 'lists:toggle-room' room.pk %}?action=add">
                    <i class="far fa-heart fa-2x text-red-600 absolute" style="z-index: 5; top:90px; right:14px;"></i>
                </a>
            {% endif %}
        {% endif %}
    </div>
    <div class="-mt-5 container max-w-full h-75vh xl:h-75vh lg:h-75vh md:h-50vh sm:h-40vh flex mb-20">
        <div class="grid grid-cols-1 xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-2 sm:grid-cols-2 w-full">
            <div class="h-full col-span-1 zoom-container">
                <div class="h-full bg-center bg-cover" style="background-image:url({{room.get_first_photo}})"></div>
            </div>
            <div class="h-full col-span-1 xl:col-span-1 lg:col-span-1 md:col-span-1 sm:col-span-1">
                <div class="grid grid-cols-2 grid-rows-2 xl:grid-cols-2 xl:grid-rows-2 lg:grid-cols-2 lg:grid-rows-2 md:grid-cols-1 md:grid-rows-2 sm:grid-cols-1 sm:grid-rows-1 h-full">
                    <div class="zoom-container col-span-1 border-gray-700 border">
                        <div style="background-image:url({{room.get_second_photo}})" class="w-full h-full bg-cover bg-center"></div>
                    </div>
                    <div class="zoom-container block xl:block lg:block md:block sm:hidden col-span-1 border-gray-700 border">
                        <div style="background-image:url({{room.get_third_photo}})" class="w-full h-full bg-cover bg-center"></div>
                    </div>
                    <div class="zoom-container block xl:block lg:block md:hidden sm:hidden col-span-1 border-gray-700 border">
                        <div style="background-image:url({{room.get_fourth_photo}})" class="w-full h-full bg-cover bg-center"></div>
                    </div>
                    <div class="zoom-container block xl:block lg:block md:hidden sm:hidden col-span-1 border-gray-700 border">
                        <div style="background-image:url({{room.get_fifth_photo}})" class="w-full h-full bg-cover bg-center"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="container px-4 xl:w-2/3 lg:w-2/3 mx-auto flex justify-around pb-56">
        <div class="w-full xl:w-1/2 lg:w-2/3 md:w-full sm:w-full">
            <div class="flex items-center justify-between">
                <div>
                    <span class="text-3xl block font-semibold">{{room.name}}</span>
                    <span class="text-lg">{{room.city}}</span>
                </div>
                <div class="flex flex-col items-center px-10">
                    <div class="flex flex-col items-center">
                        <a href="{{room.host.get_absolute_url}}">
                            {% include "mixins/user_avatar.html" with user=room.host %}
                        </a>
                    </div>
                        <span class="text-gray-500">{{room.host.first_name}}</span>
                </div>
            </div>

            <div class="flex border-section">
                <span class="mr-5 font-light font-semibold">{{room.room_type}}</span>
                <span class="mr-5 font-light">인원 {{room.guests}}명</span>
                <span class="mr-5 font-light">침실 {{room.bedrooms}}개</span>
                <span class="mr-5 font-light">침대 {{room.beds}}개</span>
                <span class="mr-5 font-light">욕실 {{room.baths}}개</span>
            </div>

            <p class="border-section">
                {{room.description}}
            </p>

            <div class="border-section">
                <h4 class="font-medium text-lg mb-5 font-semibold">편의시설</h4>
                <div class="grid grid-cols-2 row-auto">
                {% for a in room.amenities.all %}
                    <span class="col-span-1 mb-2 block">{{a}}</span>
                {% endfor %}
                </div>
            </div>

            <div class="border-section">
                <h4 class="font-medium text-lg mb-5 font-semibold">시설</h4>
                <div class="grid grid-cols-2 row-auto">
                    {% for f in room.facilities.all %}
                    <span class="col-span-1 mb-2 block">{{f}}</span>
                    {% endfor %}
                </div>
            </div>

            <div class="border-section">
                <h4 class="font-medium text-lg mb-5 font-semibold">숙소 이용 규칙</h4>
                <div class="grid grid-cols-2 row-auto">
                    {% for h in room.house_rules.all %}
                    <span class="col-span-1 mb-2 block">{{h}}</span>
                    {% endfor %}
                 </div>
            </div>

            <h4 class="font-medium text-2xl my-5 font-semibold">후기</h4>
            
            <div class="flex items-center">
                <div class="flex items-center">
                    <i class="fas fa-star text-teal-500 mr-1"></i>
                    <span class="font-bold text-xl">{{room.total_rating}}</span>
                </div>
                <div class="h-4 w-px bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{room.reviews.count}}</span>
                    <span class="text-lg">후기</span>
                </div>
            </div>
            <div class="mt-10">
                {% for review in room.reviews.all  %}
                    <div class="border-section">
                        <div class="mb-3 flex">
                            <a href="{{review.user.get_absolute_url}}">
                                {% if review.user.avatar %}
                                    <img class="h-10 w-10 xl:h-16 xl:w-16 lg:h-16 lg:w-16 md:h-12 md:w-12 sm:h-10 sm:w-10 rounded-full bg-cover bg-center" src="{{review.user.avatar.url}}">
                                {% else %}
                                    <div class="h-10 w-10 xl:h-16 xl:w-16 lg:h-16 lg:w-16 md:h-12 md:w-12 sm:h-10 sm:w-10 bg-indigo-600 rounded-full text-white flex justify-center items-center overflow-hidden">
                                        <span class="text-xl xl:text-2xl lg:text-2xl md:text-xl sm:text-xl">{{review.user.first_name|first}}</span>
                                    </div>
                                {% endif %}
                            </a>
                            <div class="flex flex-col ml-5">
                                <a href="{{review.user.get_absolute_url}}" class="font-medium">{{review.user.first_name}}</a>
                                <span class="text-sm text-gray-500">{{review.created|date:'Y년 n월'}}</span>
                            </div>
                        </div>
                        <p>{{review.review}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="px-10 w-1/3 hidden xl:blcok lg:block md:hidden sm:hidden">
            
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">숙소 수정하기</a>
            {% else %}
                
                {% for calendar in room.get_calendars %}
                <div class="mb-20">
                    <span class="text-center font-semibold text-lg block mb-8">{{calendar.year}}년 {{calendar.get_month}}</span>
                    <div class="cal-grid font-medium mb-2">
                        {% for day in calendar.day_names %}
                            <span class="font-semibold text-sm">{{day}}</span>
                        {% endfor %}
                    </div>
                    <div class="cal-grid no-drag">
                        {% for day in calendar.get_days %}
                            {% is_booked room day as is_booked_bool %}
                            {% if day.number != 0 %}
                                {% if day.past %}
                                    <span class="w-full text-center p-1 text-gray-400 font-semibold shadow-xs">{{day}}</span>
                                {% elif is_booked_bool %}
                                    <span class="w-full text-center p-1 text-gray-400 font-semibold shadow-xs line-through">{{day}}</span>
                                {% else %}
                                    <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="w-full font-semibold text-sm text-center text-gray-700 p-1 hover:bg-indigo-600 hover:text-white hover:font-medium cursor-pointer shadow-xs">{{day}}</a href="{% url 'reservations:create' room.pk day.year day.month day.number %}">
                                {% endif %}
                            {% else %}
                            <span></span>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    숙소 수정
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container no-drag lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="숙소 수정하기" %}
        <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-indigo-600 font-semibold">숙소 사진 변경하기</a>
        </div>
    </div>
{% endblock content %} 

templates/rooms/room_list.html
{% extends "base.html" %}
{% load i18n get_max_rating %}

{% block page_title %}
  {% trans '전 세계 숙소' %}
{% endblock page_title %}

{% block content %}
    <div class="absolute inset-0 bg-gray-800 bg-cover bg-center mb-25vh" style="background-image:url(https://images.unsplash.com/photo-1517166988974-5e377975dd67?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop)"></div>
    <div class="container mt-85vh px-4 mx-auto">
      <h3 class="text-xl font-semibold mb-2">{% trans "지금 가장 인기 있는 숙소" %}</h3>
      {% get_max_rating rooms as top_rating_room %}
      
      {% if top_rating_room == "-1" %}
        <span>{% trans "아직 없습니다. 많이 이용해주세요." %}</span>
      {% else %}
        {% include "mixins/room_card.html" with room=top_rating_room %}
      {% endif %}
    </div>
    <div class="container px-4 mx-auto mt-20">
      <h3 class="text-xl font-semibold mb-2">{% trans "전 세계 숙소" %}</h3>
      
      <!-- <div class="rounded-xl bg-gray-800 h-50vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1517166988974-5e377975dd67?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop)"></div> -->
      <div class="grid grid-cols-12 gap-5">
        {% for room in rooms %}
          {% include "mixins/room_card.html" with room=room %}
        {% endfor %}
      </div>
      <div class="mx-40 flex justify-between items-center my-10">
        {% if page_obj.has_previous %}
          <div class="page-transition rounded-xl w-10 h-10 bg-white text-center flex justify-center items-center border shadow-md">
            <a class="rounded-lg p-4" href="?page={{page_obj.previous_page_number}}"><svg style="display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 4; overflow: visible;" aria-hidden="true" role="presentation" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><g fill="none"><path d="m20 28-11.29289322-11.2928932c-.39052429-.3905243-.39052429-1.0236893 0-1.4142136l11.29289322-11.2928932"></path></g></svg></a>
          </div>
        {% else %}
          <div></div>
        {% endif %}

        <!-- 페이지 {{page_obj.number}} of {{page_obj.paginator.num_pages}} -->
        {% if page_obj.has_next %}
          <div class="page-transition rounded-xl w-10 h-10 bg-white text-center flex justify-center items-center border shadow-md">
            <a class="rounded-lg p-4" href="?page={{page_obj.next_page_number}}"><svg aria-hidden="true" role="presentation" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" style="display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 4; overflow: visible;"><g fill="none"><path d="m12 4 11.2928932 11.2928932c.3905243.3905243.3905243 1.0236893 0 1.4142136l-11.2928932 11.2928932"></path></g></svg></a>
          </div>
        {% else %}
          <div></div>
        {% endif %}
      </div>
      </div><div class="hidden xl:block lg:block">
        {% include "partials/footer.html" %}
      </div>
    
{% endblock content %}


templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}의 사진
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">

        <div class="my-10 w-full flex justify-end">
            <div class="flex flex-col items-center justify-center px-6"><a href="{% url 'rooms:add-photo' room.pk %}" class=" w-1/6 block"><i class="fa fa-camera fa-3x hover:text-black"></i></a></div>
        </div>

        {% for photo in room.photos.all  %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-teal-500" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">수정하기</a>
                    <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">삭제하기</a>
                </div>
            </div>
        {% endfor %}

        <div class="flex justify-center mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-indigo-600 font-semibold text-xl">숙소 수정화면</a>
        </div>

    </div>
{% endblock content %} 