config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rooms import views as room_views
from users import views as user_views


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"


urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]


reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("list/", views.seeReservationView.as_view(), name="see-reservation"),
]


reservations/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):
    day = models.DateField(verbose_name="예약 날짜")
    reservation = models.ForeignKey(
        "Reservation", verbose_name="예약", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "예약일"
        verbose_name_plural = "예약일"

    def __str__(self):
        return str(self.day)


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "대기 중"),
        (STATUS_CONFIRMED, "수락됨"),
        (STATUS_CANCELED, "취소됨"),
    )

    status = models.CharField(
        max_length=12,
        choices=STATUS_CHOICES,
        default=STATUS_PENDING,
        verbose_name="예약 상태",
    )

    check_in = models.DateField(verbose_name="체크인")
    check_out = models.DateField(verbose_name="체크아웃")
    guest = models.ForeignKey(
        "users.User",
        related_name="reservations",
        on_delete=models.CASCADE,
        verbose_name="게스트",
    )
    room = models.ForeignKey(
        "rooms.Room",
        related_name="reservations",
        on_delete=models.CASCADE,
        verbose_name="숙소",
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        if self.status != "canceled":
            # return now >= self.check_in and now <= self.check_out
            return now <= self.check_out
        elif self.status == "canceled":
            return False

    in_progress.boolean = True
    in_progress.short_description = "진행중"

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True
    is_finished.short_description = "만료됨"

    def get_now(self):
        return timezone.now().date()

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end), reservation__room=self.room
            ).exists()

            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return

        return super().save(*args, **kwargs)

    class Meta:

        verbose_name = "예약"
        verbose_name_plural = "예약"
        ordering = ["created"]

reviews/forms.py
from django import forms
from . import models


class CreateReviewForm(forms.ModelForm):
    accuracy = forms.IntegerField(min_value=1, max_value=5)
    communication = forms.IntegerField(min_value=1, max_value=5)
    cleanliness = forms.IntegerField(min_value=1, max_value=5)
    location = forms.IntegerField(min_value=1, max_value=5)
    check_in = forms.IntegerField(min_value=1, max_value=5)
    value = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = models.Review
        fields = (
            "review",
            "accuracy",
            "communication",
            "cleanliness",
            "location",
            "check_in",
            "value",
        )

    def save(self):
        review = super().save(commit=False)
        return review

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View, TemplateView
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from rooms import models as room_models
from reviews import forms as review_forms
from . import models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "이 숙소는 예약할 수 없습니다.")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        messages.success(request, "해당 날짜로 예약되었습니다. 호스트가 승인하면 예약이 확정됩니다.")
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation:
            raise Http404()
        if not reservation or (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404()
        form = review_forms.CreateReviewForm()

        return render(
            self.request,
            "reservations/reservation_detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):

    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()

    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
        reservation.save()
        messages.success(request, "예약이 완료되었습니다.")
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        models.BookedDay.objects.filter(reservation=reservation).delete()
        reservation.save()
        messages.info(request, "예약이 취소되었습니다.")

    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class seeReservationView(TemplateView):
    template_name = "reservations/reservation_list.html"

templates/reservations/reservation_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
    {{reservation.check_in}} 예약
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="py-20">
    <div class="grid grid-cols-3 grid-rows-2 grid-flow-col container xl:w-9/12 mx-auto rounded-t-lg h-full xl:h-60vh lg:h-60vh md: h-85vh sm:h-full mb-48">
        <div class="w-full h-full col-span-3 row-span-1 xl:col-span-2 xl:row-span-2 lg:col-span-2 lg:row-span-2 md: col-span-3 md:row-span-1 sm:col-span-3 sm:row-span-1">
            <div class="bg-cover bg-center h-full" style="background-image: url({{reservation.room.get_first_photo}});"></div>
        </div>
        
        
        <div class="col-span-3 row-span-1 xl:row-span-2 lg:row-span-2 md:row-span-1 sm:row-span-1 xl:col-span-1 lg:col-span-2 md: col-span-3 sm:col-span-3 flex flex-col items-start border-l border-t">
            <div class="font-semibold border-b py-8 px-5 w-full border-r">
                예약 날짜: <span class="text-sm text-gray-600">{{reservation.check_in|date:'Y년 n월 d일'}} - {{reservation.check_out|date:'Y년 n월 d일'}}</span><span class="ml-5 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}{% if reservation.status == 'pending' and reservation.get_now > reservation.check_in %}<i class="fa fa-exclamation text-red-500 ml-1"></i>{% endif %}</span>
            </div>

            <span class="text-2xl border-b border-r p-5 w-full">
                {{reservation.room.name}}
            </span>

            <div class="flex flex-col justify-between p-5 border-b h-full border-r w-full">
                <div class="flex">
                    <div class="flex flex-col items-center">
                        {% include "mixins/user_avatar.html" with user=reservation.room.host %}
                        <span class="mt-2 text-gray-500">{{reservation.room.host.first_name}}</span>
                    </div>
                    <div class="ml-5 flex flex-col">
                        
                        {% if reservation.room.host == user %}
                        <span class="font-medium mb-px">게스트에게 연락하기</span>
                        {% else %}
                        <span class="font-medium mb-px">호스트에게 연락하기</span>
                        {% endif %}
                        <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="font-medium text-indigo-600">메세지 보내기</a>
                    </div>
                </div>
                
                
                {% if reservation.status != 'canceled' %}
                    {% if reservation.status == 'confirmed' and reservation.is_finished %}
                    
                    {% else %}
                        <div class="flex self-end">
                            {% if reservation.status == 'pending' %}
                                {% if reservation.room.host == user %}
                                    <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="btn-link block px-3 mx-3">예약 확정</a>
                                {% else %}
                                    {% if reservation.get_now < reservation.check_in %}
                                        <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="btn-link bg-red-500 block px-3">예약 취소</a>
                                    {% endif %}
                                {% endif %}
                                
                            {% endif %}
                        </div>
                    {% endif %}
                        
                {% endif %}
            </div>
            
        </div>
        
    </div>
    <div class="container mx-auto">
    {% if reservation.status != 'canceled' %}
        {% if reservation.status == 'confirmed' and reservation.is_finished %}
        <span class="font-medium text-2xl text-center w-full block mb-5">후기 작성</span>
        <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto">
            {% csrf_token %}
            
            {{form.review.label}}
            <div class="input-box">
                {{form.review}}
            </div>
                <div class="flex justify-around">
                        
                    <div class="w-full mr-2">
                        <div>
                            <span>{% trans "정확성" %}</span>
                            <div class="input-box col-span-2">
                                <input type="number" min="1" max="5" name="accuracy" required="" id="id_accuracy">
                            </div>
                        </div>
                            
                        <div>
                            <span>{% trans "의사소통" %}</span>
                            <div class="input-box col-span-2">
                                <input type="number" min="1" max="5" name="communication" required="" id="id_communication">
                            </div>
                        </div>

                        
                        <div>
                            <span>{% trans "청결도" %}</span>
                            <div class="input-box col-span-2">
                                <input type="number" min="1" max="5" name="cleanliness" required="" id="id_cleanliness">
                            </div>
                        </div>
                    </div>

                    <div class="w-full ml-2">
                        <div>
                            <span>{% trans "위치" %}</span>
                            <div class="input-box col-span-2">
                                <input type="number" min="1" max="5" name="location" required="" id="id_location">
                            </div>
                        </div>

                        
                        <div>
                            <span>{% trans '체크인' %}</span>
                            <div class="input-box col-span-2">
                                <input type="number" min="1" max="5" name="check_in" required="" id="id_check_in">
                            </div>
                        </div>

                        <div>
                            <span>{% trans '가치' %}</span>
                            <div class="input-box col-span-2">
                                <input type="number" min="1" max="5" name="value" required="" id="id_value">
                            </div>
                        </div>
                    </div>
                </div>
            <button class="btn-link mt-5">후기 작성 완료</button>
        </form>
        {% endif %}
    {% endif %}
    </div>
</div>
{% endblock content %} 

templates/reservations/reservation_list.html
{% extends "base.html" %}
{% load i18n get_guest_reservation get_reservation_false get_in_progress get_reservation_len %}
{% block page_title %}
    {{user.first_name}}의 예약한 숙소
{% endblock page_title %}

{% block content %}
        
        <div class="container xl:w-3/5 lg:w-2/3 md:w-3/4 mx-auto my-10 flex flex-col p-6 min-h-75vh">

            {% get_guest_reservation user as guset_reservations %}

            <h3 class="font-semibold text-lg border-b border-black mb-10 pb-6">{% trans "내 숙소 예약 관리" %}</h3>
            
            <div class="grid grid-cols-12 gap-5">
                
                {% if guset_reservations == "-1" %}
                    <span class="col-span-12 block w-full mb-25vh">{% trans "아직 없습니다." %}</span>
                {% else %}
                    {% for reservation in guset_reservations %}
                        {% if reservation.is_finished %}

                        {% else %}

                            {% if reservation.status != 'canceled' and reservation.is_finished == False %}
                            
                            <div class="w-full col-span-12 xl:col-span-3 lg:col-span-4 md:col-span-6 sm:col-span-12 mb-10 
                                    
                                    ">
                                <a href="{% url 'reservations:detail' reservation.pk %}" >
                                    <div
                                    class="w-full h-64 bg-cover bg-center rounded-lg mb-2"
                                    style="background-image: url({{reservation.room.get_first_photo}})"
                                    ></div>
                                    <div class="flex justify-between mb-2">
                                    <div class="overflow-text">
                                        {% if reservation.room.host.superhost %}
                                            <span class="mr-px uppercase font-medium text-xs border border-black text-black rounded py-px px-1">{% trans '슈퍼호스트' %}</span>
                                        {% endif %}
                                            
                                        <span class="text-sm text-gray-600">{{reservation.room.city}} {{reservation.room.country.name}}</span>
                                    </div>
                                    {% if reservation.room.reviews.count != 0 %}
                                        <span class="text-sm flex items-center">
                                            <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{reservation.room.total_rating}}
                                        </span>
                                    {% endif %}
                                    </div>
                                    <a href="{% url 'reservations:detail' reservation.pk %}">{{reservation}}</a>
                                </a>
                            </div>
                            {% endif %}
                        {% endif %}
                
                    {% endfor %}
                {% endif %}
            </div>

            
            {% get_reservation_false user.reservations.all as get_reservation_false_bool %}

            <h3 class="font-semibold text-lg border-b border-black mb-10 pb-6">{% trans "예약한 숙소" %}</h3>
            <div class="grid grid-cols-12 gap-5">

                {% if get_reservation_false_bool %}
                    <span class="col-span-12 block w-full mb-25vh">{% trans "아직 없습니다." %}</span>
                
                {% else %}
                    

                {% for reservation in user.reservations.all %}
                    {% if reservation.is_finished %}

                    {% else %}


                        {% if reservation.status != 'canceled' and reservation.is_finished == False %}
                            
                            <div class="w-full col-span-12 xl:col-span-3 lg:col-span-4 md:col-span-6 sm:col-span-12 mb-10 
                                    
                                    ">
                                <a href="{% url 'reservations:detail' reservation.pk %}" >
                                    <div
                                    class="w-full h-64 bg-cover bg-center rounded-lg mb-2"
                                    style="background-image: url({{reservation.room.get_first_photo}})"
                                    ></div>
                                    <div class="flex justify-between mb-2">
                                    <div class="overflow-text">
                                        {% if reservation.room.host.superhost %}
                                            <span class="mr-px uppercase font-medium text-xs border border-black text-black rounded py-px px-1">{% trans '슈퍼호스트' %}</span>
                                        {% endif %}
                                            
                                        <span class="text-sm text-gray-600">{{reservation.room.city}} {{reservation.room.country.name}}</span>
                                    </div>
                                    {% if reservation.room.reviews.count != 0 %}
                                        <span class="text-sm flex items-center">
                                            <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{reservation.room.total_rating}}
                                        </span>
                                    {% endif %}
                                    </div>
                                    <a href="{% url 'reservations:detail' reservation.pk %}">{{reservation}}</a>
                                </a>
                            </div>
                            
                        {% endif %}
                    {% endif %}
                {% endfor %}
                {% endif %}
            </div>
            
            
            
            {% get_reservation_len user.reservations.all as get_reservation_len_bool %}
            {% get_in_progress user.reservations.all as get_in_progress_bool %}

            <h3 class="font-semibold text-lg border-b border-black mb-10 pb-6">{% trans "과거에 예약한 숙소" %}</h3>
            <div class="grid grid-cols-12 gap-5">

                {% if get_reservation_len_bool or get_in_progress_bool %}
                    <span class="col-span-12 block w-full mb-25vh">{% trans "아직 없습니다." %}</span>
                {% else %}

                {% for reservation in user.reservations.all %}
                    {% if reservation.is_finished %}
                        <div class="w-full col-span-12 xl:col-span-3 lg:col-span-4 md:col-span-6 sm:col-span-12 mb-10 opacity-50 
                                
                                ">
                            <a href="{% url 'reservations:detail' reservation.pk %}" >
                                <div
                                class="w-full h-64 bg-cover bg-center rounded-lg mb-2"
                                style="background-image: url({{reservation.room.get_first_photo}})"
                                ></div>
                                <div class="flex justify-between mb-2">
                                <div class="overflow-text">
                                    {% if reservation.room.host.superhost %}
                                        <span class="mr-px uppercase font-medium text-xs border border-black text-black rounded py-px px-1">{% trans '슈퍼호스트' %}</span>
                                    {% endif %}
                                        
                                    <span class="text-sm text-gray-600">{{reservation.room.city}} {{reservation.room.country.name}}</span>
                                </div>
                                {% if reservation.room.reviews.count != 0 %}
                                    <span class="text-sm flex items-center">
                                        <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{reservation.room.total_rating}}
                                    </span>
                                {% endif %}
                                </div>
                                <a href="{% url 'reservations:detail' reservation.pk %}">{{reservation}}</a>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>

{% endblock content %} 