config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rooms import views as room_views
from users import views as user_views


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservation")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"


urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]


lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]


reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("list/", views.seeReservationView.as_view(), name="see-reservation"),
]


users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("login/naver/", views.naver_login, name="naver-login"),
    path("login/naver/callback/", views.naver_callback, name="naver-callback"),
    # path("login/google/", views.google_login, name="google-login"),
    # path("login/google/callback/", views.google_callback, name="google-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>", views.UserProfileView.as_view(), name="profile"),
    path("switch-language/", views.switch_language, name="switch-language"),
]


users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "이메일", "autocomplete": "off"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호", "autocomplete": "off"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("잘못된 비밀번호입니다."))

        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("계정이 존재하지 않습니다."))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "email")
        widgets = {
            "first_name": forms.TextInput(
                attrs={"placeholder": _("이름"), "autocomplete": "off"}
            ),
            "email": forms.EmailInput(
                attrs={"placeholder": _("이메일"), "autocomplete": "off"}
            ),
        }

    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput(
            attrs={"placeholder": _("비밀번호"), "autocomplete": "off"}
        ),
    )
    password1 = forms.CharField(
        label="비밀번호 확인",
        widget=forms.PasswordInput(
            attrs={"placeholder": _("비밀번호 확인"), "autocomplete": "off"}
        ),
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("이미 사용중인 이메일입니다.", code="existing_user")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        min_length = 8
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        print(self.cleaned_data)
        print(password, password1)
        if len(password) < min_length:
            raise forms.ValidationError("비밀번호를 최소 8자리 이상으로 해주세요.")
        if password != password1:
            raise forms.ValidationError("비밀번호가 서로 다릅니다.")
        if not any(char.isdigit() for char in password):
            raise forms.ValidationError("최소 1자리 이상의 숫자를 포함해주세요.")
        if not any(char.isalpha() for char in password):
            raise forms.ValidationError("최소 1자리 이상의 알파벳을 포함해주세요.")

        return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
import uuid
from django.utils import translation
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponse
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, _("로그인에 성공하였습니다."))
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    messages.success(request, _("성공적으로 로그아웃 되었습니다."))
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, _("로그인에 성공하였습니다."))
        # user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
    except models.user.DoesNotExist:
        pass

    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://django-booking.eba-a3mcndmb.ap-northeast-2.elasticbeanstalk.com/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("토큰을 가져오지 못하였습니다.")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    f"https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException("이미 가입된 이메일 주소입니다.")
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, _("로그인에 성공하였습니다."))
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("프로필을 얻을 수 없습니다.")
        else:
            raise GithubException("코드를 얻을 수 없습니다.")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class KakaoException(Exception):
    pass


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://django-booking.eba-a3mcndmb.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://django-booking.eba-a3mcndmb.ap-northeast-2.elasticbeanstalk.com/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("코드를 얻을 수 없습니다.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        kakao_account = profile_json.get("kakao_account")
        email = kakao_account.get("email", None)
        if email is None:
            raise KakaoException("로그인을 위한 이메일을 제공해주세요.")
        profile = kakao_account.get("profile")
        nickname = profile.get("nickname")
        profile_image = profile.get("profile_image_url")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException("이미 가입된 이메일 주소입니다.")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
            if profile_image is not None:
                photo_request = requests.get(profile_image)
                user.avatar.save(
                    f"{nickname}-avatar", ContentFile(photo_request.content)
                )
        login(request, user)
        messages.success(request, _("로그인에 성공하였습니다."))
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class NaverException(Exception):
    pass


def naver_login(request):
    client_id = os.environ.get("NAVER_ID")
    state = uuid.uuid4().hex[:16]
    redirect_uri = "http://django-booking.eba-a3mcndmb.ap-northeast-2.elasticbeanstalk.com/users/login/naver/callback"
    return redirect(
        f"https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}&state={state}"
    )


def naver_callback(request):
    try:
        code = request.GET.get("code")
        state = request.GET.get("state")
        client_id = os.environ.get("NAVER_ID")
        client_secret = os.environ.get("NAVER_SECRET")
        redirect_uri = "http://django-booking.eba-a3mcndmb.ap-northeast-2.elasticbeanstalk.com/users/login/naver/callback"
        token_request = requests.get(
            f"https://nid.naver.com/oauth2.0/token?grant_type=authorization_code&client_id={client_id}&client_secret={client_secret}&code={code}&state={state}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise NaverException("코드를 얻을 수 없습니다.")

        access_token = token_json.get("access_token")
        refresh_token = token_json.get("refresh_token")
        print(access_token)
        profile_request = requests.get(
            "https://openapi.naver.com/v1/nid/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        response = profile_json.get("response")
        email = response.get("email")
        name = response.get("name")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_NAVER:
                raise NaverException("이미 가입된 이메일 주소입니다.")
        except models.User.DoesNotExist:

templates/users/login.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
  {% trans '로그인' %}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container xl:w-1/4 lg:w-5/12 md:w-1/2 mx-auto my-32 flex flex-col items-center border p-6 border-gray-400">
      {% include 'partials/social_login.html' %}
      <form method="POST" class="w-full" enctype="multipart/form-data">
        {% csrf_token %}
          {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
                  <span class="text-red-700 font-semibold text-sm block">{{error}}</span> 
              {% endfor %}
          {% endif %}
          <div class="input-box {% if field.errors%}has_error{% endif %}">
            <input type="email" name="email" placeholder="{% trans '이메일' %}" autocomplete="off" required="" id="id_email"><div class="px-2"><svg viewBox="0 0 24 24" role="presentation" aria-hidden="true" focusable="false" style="height: 1em; width: 1em; display: block; fill: currentcolor;"><path d="m22.5 4h-21c-.83 0-1.5.67-1.5 1.51v12.99c0 .83.67 1.5 1.5 1.5h20.99a1.5 1.5 0 0 0 1.51-1.51v-12.98c0-.84-.67-1.51-1.5-1.51zm.5 14.2-6.14-7.91 6.14-4.66v12.58zm-.83-13.2-9.69 7.36c-.26.2-.72.2-.98 0l-9.67-7.36h20.35zm-21.17.63 6.14 4.67-6.14 7.88zm.63 13.37 6.3-8.1 2.97 2.26c.62.47 1.57.47 2.19 0l2.97-2.26 6.29 8.1z" fill-rule="evenodd"></path></svg></div>
          </div>
          <div class="input-box {% if field.errors%}has_error{% endif %}">
            <input type="password" name="password" placeholder="{% trans '비밀번호' %}" autocomplete="off" required="" id="id_password"><div class="px-2"><svg viewBox="0 0 24 24" role="presentation" aria-hidden="true" focusable="false" style="height: 1em; width: 1em; display: block; fill: currentcolor;"><path d="m19.5 9h-.5v-2a7 7 0 1 0 -14 0v2h-.5c-.78 0-1.5.72-1.5 1.5v12c0 .78.72 1.5 1.5 1.5h15c .78 0 1.5-.72 1.5-1.5v-12c0-.78-.72-1.5-1.5-1.5zm.5 13.5c0 .22-.28.5-.5.5h-15c-.22 0-.5-.28-.5-.5v-12c0-.22.28-.5.5-.5h1a .5.5 0 0 0 .5-.5v-2.5a6 6 0 1 1 12 0v2.5a.5.5 0 0 0 .5.5h1c .22 0 .5.28.5.5zm-8-10.5a3 3 0 0 0 -3 3c0 .83.36 1.59.94 2.15l-.9 2.16a.5.5 0 0 0 .46.69h5a .5.5 0 0 0 .46-.69l-.87-2.19c.56-.55.91-1.31.91-2.13a3 3 0 0 0 -3-3zm1.04 5.19.72 1.81h-3.51l.74-1.79a.5.5 0 0 0 -.17-.6 2 2 0 1 1 3.18-1.61c0 .64-.31 1.24-.8 1.6a.5.5 0 0 0 -.17.59zm-1.04-14.19a4 4 0 0 0 -4 4v2.5a.5.5 0 0 0 .5.5h7a .5.5 0 0 0 .5-.5v-2.5a4 4 0 0 0 -4-4zm3 6h-6v-2a3 3 0 1 1 6 0z" fill-rule="evenodd"></path></svg></div>
          </div>
          {% if field.errors and field != form.password1 %}
              {% for error in field.errors %}
                  <span class="text-red-700 font-semibold text-sm block">{{error}}</span> 
              {% endfor %}
          {% endif %}
          <button class="btn bg-indigo-600 text-white font-semibold {% if form.currency %}mt-3{% endif %}">{% trans "로그인" %}</button>
        </form>

      <div class="mt-5">
        <span class="mr-2">{% trans '계정이 없으신가요' %}?</span>
        <a href="{% url 'users:signup' %}" class="text-indigo-500 font-semibold">{% trans '회원가입' %}</a>
      </div>
    </div>

{% endblock content %} 


templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
  {% trans '회원가입' %}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container xl:w-1/4 lg:w-5/12 md:w-1/2 mx-auto my-32 flex flex-col items-center border p-6 border-gray-400">
      {% include 'partials/social_login.html' %}
      <form method="POST" class="w-full" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <span class="text-red-700 font-semibold text-sm block">{{error}}</span> 
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {% include 'mixins/auth/form_input.html' with field=field %}
        {% endfor %}
        <button class="btn bg-indigo-600 text-white font-semibold {% if form.currency %}mt-3{% endif %}">{% trans "회원가입" %}</button>
    </form>

      <div class="mt-5">
        <span class="mr-2">{% trans "이미 계정이 있으신가요" %}?</span>
        <a href="{% url 'users:login' %}" class="text-indigo-500 font-semibold">{% trans "로그인" %}</a>
      </div>
    </div>

{% endblock content %} 


templates/users/update-profile.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
  프로필 수정
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container no-drag xl:w-1/4 lg:w-5/12 md:w-1/2 mx-auto my-32 flex flex-col items-center border p-6 border-gray-400">

      <form method="POST" class="w-full" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <span class="text-red-700 font-semibold text-sm block">{{error}}</span> 
            {% endfor %}
        {% endif %}
        {% for field in form %}
            {% include 'mixins/auth/form_input.html' with field=field cta="수정하기" %}
        {% endfor %}
        <button class="btn bg-indigo-600 text-white font-semibold {% if form.currency %}mt-3{% endif %}">{% trans '수정하기' %}</button>
    </form>
      
      {% if user_obj.login_method == "email" %}
        
        <div class="mt-5">
          <a href="{% url 'users:password' %}" class="text-indigo-600 font-semibold">{% trans '비밀번호 변경하기' %}</a>
        </div>
      {% endif %}
        
    </div>

{% endblock content %} 


templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}
    {% trans '프로필' %}
{% endblock page_title %}

{% block content %}

    <div class="container xl:w-3/5 lg:w-2/3 md:w-3/4 mx-auto my-10 flex flex-col p-6 min-h-75vh">
        <h3 class="font-semibold text-lg border-b border-black mb-10 pb-6">{% trans "프로필" %}</h3>
        <div class="grid grid-cols-5 border-t border-b border-gray-400 min-h-50vh w-full">
            <div class="col-span-1 pl-2 text-gray-600 bg-gray-100 border-b border-r border-gray-400 flex items-center font-semibold">{% trans "프로필 사진" %}</div>
            <div class="col-span-4 pl-2 text-gray-800 text-sm border-b border-gray-400 flex items-center">
                {% if user_obj.avatar %}
                    <div class="h-24 w-24 xl:h-32 xl:w-32 lg:h-32 lg:w-32 md: h-24 md:w-24 sm:w-24 sm:h-24" ><img src="{{user_obj.avatar.url}}" class="h-24 w-24 xl:h-32 xl:w-32 lg:h-32 lg:w-32 md: h-24 md:w-24 sm:w-24 sm:h-24 bg-cover rounded-full" /></div>
                {% else %}
                    <div class="h-24 w-24 xl:h-32 xl:w-32 lg:h-32 lg:w-32 md: h-24 md:w-24 sm:w-24 sm:h-24 bg-indigo-600 rounded-full text-white flex justify-center items-center overflow-hidden">
                        <span class="{{text|default:'text-3xl'}}">{{user_obj.first_name|first}}</span>
                    </div>
                {% endif %}
            </div>
            <div class="col-span-1 pl-2 text-gray-600 bg-gray-100 border-gray-400 border-b border-r flex items-center font-semibold">{% trans "이름" %}</div>
            <div class="col-span-4 pl-2 text-gray-800 border-b text-sm flex border-gray-400 items-center">
                {{user_obj.first_name}}
                {% if user_obj.superhost %}
                    <i class="fas fa-star text-red-500 ml-1"></i>
                {% endif %}
            </div>
            <div class="col-span-1 pl-2 text-gray-600 bg-gray-100 border-r border-gray-400 flex items-center font-semibold">{% trans "소개" %}</div>
            <div class="col-span-4 pl-2 flex items-center">{{user_obj.bio}}</div>
        </div>
        <div class="flex pt-10 pb-0 justify-center">
            {% if user == user_obj %}
            <div class="w-64 mx-auto py-5 flex justify-end">
                <div class="flex flex-col justify-center items-center"><a href="{% url 'lists:see-favs' %}" class="icon-ani"><i class="fa fa-heart text-red-600 fa-2x mb-5 icon-ani hover:text-red-700"></i></a><span class="font-semibold text-sm text-gray-700">{% trans "마음에 든 숙소" %}</span></div>
            </div>
            <div class="w-64 mx-auto py-5 flex justify-center">
                <div class="flex flex-col justify-center items-center"><a href="{% url 'reservations:see-reservation' %}" class="icon-ani"><i class="fa fa-book text-naver fa-2x mb-5 icon-ani hover:text-green-600"></i></a><span class="font-semibold text-sm text-gray-700">{% trans "숙소 예약 관리" %}</span></div>
            </div>
            
            <div class="w-64 mx-auto py-5 flex justify-start">
                <div class="flex flex-col justify-center items-center"><a href="{% url 'users:update' %}" class="icon-ani"><i class="fa fa-user-edit text-gray-800 fa-2x mb-5 icon-ani hover:text-black"></i></a><span class="font-semibold text-sm text-gray-700">{% trans "프로필 수정" %}</span></div>
            </div>
            {% endif %}
        </div>
    </div>
    
    {% if user_obj.rooms.count > 0 %}
    <div class="container xl:w-3/5 lg:w-2/3 md:w-3/4 mx-auto my-10 flex flex-col p-6 min-h-75vh">
        <h3 class="font-semibold text-lg border-b border-black mb-10 pb-6">{{user_obj.first_name}}{% trans "의 숙소" %}</h3>
        <div class="grid grid-cols-12 gap-5">
            {% for room in user_obj.rooms.all %}
                {% include "mixins/room_card.html" with room=room %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock content %} 